src/Entity/Tareas.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TareasRepository")
 */
class Tareas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Listas", inversedBy="tareas")
     */
    private $lista;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="text")
     */
    private $nota;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_vencimiento;

    /**
     * @ORM\Column(type="boolean")
     */
    private $importante;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLista(): ?Listas
    {
        return $this->lista;
    }

    public function setLista(?Listas $lista): self
    {
        $this->lista = $lista;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNota(): ?string
    {
        return $this->nota;
    }

    public function setNota(string $nota): self
    {
        $this->nota = $nota;

        return $this;
    }

    public function getFechaVencimiento(): ?\DateTimeInterface
    {
        return $this->fecha_vencimiento;
    }

    public function setFechaVencimiento(\DateTimeInterface $fecha_vencimiento): self
    {
        $this->fecha_vencimiento = $fecha_vencimiento;

        return $this;
    }

    public function getImportante(): ?bool
    {
        return $this->importante;
    }

    public function setImportante(bool $importante): self
    {
        $this->importante = $importante;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }
}

src/Form/TareasType.php
<?php

namespace App\Form;

use App\Entity\Tareas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TareasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('nota')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tareas::class,
        ]);
    }
}

src/Controller/TareasController.php
<?php
namespace App\Controller;
header("Access-Control-Allow-Origin: *");
use App\Entity\Listas;
use App\Entity\Tareas;
use App\Form\TareasType;
use App\Repository\ListasRepository;
use App\Repository\TareasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;

/**
 * @Route("/tareas")
 */
class TareasController extends AbstractController
{
    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
        $encoders = [new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $this->serializer = new Serializer($normalizers, $encoders);
    }

    /**
     * @Route("/", name="tareas_index", methods={"GET"})
     */
    public function index(TareasRepository $tareasRepository, ListasRepository $listasRepository, Request $request): Response
    {
        $idList = $request->query->get('id');
        if ($idList != null) {
            $this->session->set('lista', $idList);
        }

        if ($this->session->get('lista') == null) {
            return $this->redirectToRoute('listas_index');
        }

        return $this->render('tareas/index.html.twig', [
            'tareas' => $tareasRepository->findBy(['lista' => $this->session->get('lista')]),
            'listas' => $listasRepository->findBy(['usuario' => $this->session->get('idUser')]),
        ]);
    }

    /**
     * @Route("/new", name="tareas_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->session->get('lista') == null) {
            return $this->redirectToRoute('listas_index');
        }
        $tarea = new Tareas();
        $form = $this->createForm(TareasType::class, $tarea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $tarea->setFechaVencimiento(new \DateTime());
            $tarea->setEstado('abierto');

            $repository = $this->getDoctrine()->getRepository(Listas::class);
            $lista = $repository->find($this->session->get('lista'));

            $tarea->setLista($lista);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tarea);
            $entityManager->flush();

            return $this->redirectToRoute('tareas_index');
        }

        return $this->render('tareas/new.html.twig', [
            'tarea' => $tarea,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tareas_show", methods={"GET"})
     */
    public function show(Tareas $tarea): Response
    {
        return $this->render('tareas/show.html.twig', [
            'tarea' => $tarea,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tareas_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tareas $tarea): Response
    {
        $form = $this->createForm(TareasType::class, $tarea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tareas_index');
        }

        return $this->render('tareas/edit.html.twig', [
            'tarea' => $tarea,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tareas_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tareas $tarea): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tarea->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tarea);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tareas_index');
    }

    /**
     * @Route("/api/autocomplete", name="tareas_autocomplet", methods={"GET"})
     */
    public function autcomplete(Request $request, TareasRepository $tareasRepository) {
        $word = $request->query->get('word');
        $tareas = $tareasRepository->findAllMatching($word);
        $responseData = [
            'status' => true,
            'data'   => $tareas
        ];
        
        return new Response(json_encode($responseData));
    }
}

templates/tareas/_delete_form.html.twig
<form method="post" action="{{ path('tareas_delete', {'id': tarea.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tarea.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/tareas/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
   
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tareas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tareas{% endblock %}

{% block body %}
    <div class="back-title">
        <a class="waves-effect blue lighten-4 btn-flat btn-back" href="{{ path('tareas_index') }}"><i class="material-icons">keyboard_arrow_left</i></a>
        <h4>Editar tarea</h4>
    </div>

    {{ include('tareas/_form.html.twig', {'button_label': 'Actualizar'}) }}
{% endblock %}

templates/tareas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tareas index
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link href="{{ asset('css/tareas.css') }}" rel="stylesheet"/>
	<link href="{{ asset('css/utilities.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
	{{ parent() }}

	<div class="row">
		<div class="col s1">
			<div class="row m-16">
				<a href="#" data-target="slide-out" class="sidenav-trigger">
					<i class="material-icons">menu</i>
				</a>
			</div>
		</div>
		<div class="col s10">
			<div class="row">
				<div class="input-field col s12">
					<i class="material-icons prefix">textsms</i>
					<input type="text" id="autocomplete-input" class="autocomplete">
					<label for="autocomplete-input">Buscar tareas</label>
				</div>
			</div>
		</div>
	</div>

	<ul id="slide-out" class="sidenav">
		<li>
			<a class="subheader">Listas</a>
		</li>

		{% for lista in listas %}
			<li>
				<a class="waves-effect" href="{{ path('tareas_index') }}?id={{lista.id}}">{{ lista.nombre }}</a>
			</li>
		{% else %}
			<p>Usuario sin lista</p>
		{% endfor %}

		<li>
			<a class="waves-effect waves-light btn" href="{{ path('listas_new') }}">Crear lista nueva</a>
		</li>
	</ul>

	<div class="top">
		<h3>Tareas</h3>
		<a class="btn-large waves-effect waves-light red" href="{{ path('tareas_new') }}">Nueva tarea</a>
	</div>
    
	<ul class="collapsible">
		{% for tarea in tareas %}
			<li>
				<div class="collapsible-header">
					<i class="material-icons">filter_drama</i>{{ tarea.nombre }}</div>
				<div class="collapsible-body">
					<p>{{ tarea.nota }}</p>
                    <div>
                        <a class="waves-effect waves-light btn" href="{{ path('tareas_edit', {'id': tarea.id}) }}">Editar</a>
                        <a class="waves-effect waves-light btn" href="{{ path('tareas_show', {'id': tarea.id}) }}">Ver detalles</a>
                    </div>
				</div>
			</li>
		{% endfor %}
	</ul>
	{% block javascripts %}
		{{ parent() }}
		<script src="{{ asset('js/tareas.js') }}"></script>
		<script src="{{ asset('js/autocomplete.js') }}"></script>
	{% endblock %}
{% endblock %}

templates/tareas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tareas{% endblock %}

{% block body %}
    
    <div class="back-title">
        <a class="waves-effect blue lighten-4 btn-flat btn-back" href="{{ path('tareas_index') }}"><i class="material-icons">keyboard_arrow_left</i></a>
        <h4>Crear tarea</h4>
    </div>

    {{ include('tareas/_form.html.twig') }}
{% endblock %}

templates/tareas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ tarea.nombre }}{% endblock %}

{% block body %}
    <div class="back-title">
        <a class="waves-effect blue lighten-4 btn-flat btn-back" href="{{ path('tareas_index') }}"><i class="material-icons">keyboard_arrow_left</i></a>
        <h4>Tarea {{ tarea.nombre }}</h4>
    </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tarea.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ tarea.nombre }}</td>
            </tr>
            <tr>
                <th>Nota</th>
                <td>{{ tarea.nota }}</td>
            </tr>
            <tr>
                <th>Fecha_vencimiento</th>
                <td>{{ tarea.fechaVencimiento ? tarea.fechaVencimiento|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Importante</th>
                <td>{{ tarea.importante ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ tarea.estado }}</td>
            </tr>
        </tbody>
    </table>
    <div class="bottom">
        <a class="waves-effect waves-light btn btn-editar" href="{{ path('tareas_edit', {'id': tarea.id}) }}">Editar</a>

        {{ include('tareas/_delete_form.html.twig') }}
    </div>
    
{% endblock %}