src/Entity/Listas.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ListasRepository")
 */
class Listas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuario", inversedBy="listas")
     * @ORM\JoinColumn(name="usuario_id", referencedColumnName="id")
     */
    private $usuario;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_creacion;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tareas", mappedBy="lista")
     */
    private $tareas;

    public function __construct()
    {
        $this->tareas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario($usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    /**
     * @return Collection|Tareas[]
     */
    public function getTareas(): Collection
    {
        return $this->tareas;
    }

    public function addTarea(Tareas $tarea): self
    {
        if (!$this->tareas->contains($tarea)) {
            $this->tareas[] = $tarea;
            $tarea->setLista($this);
        }

        return $this;
    }

    public function removeTarea(Tareas $tarea): self
    {
        if ($this->tareas->contains($tarea)) {
            $this->tareas->removeElement($tarea);
            // set the owning side to null (unless already changed)
            if ($tarea->getLista() === $this) {
                $tarea->setLista(null);
            }
        }

        return $this;
    }
}

src/Form/ListasType.php
<?php

namespace App\Form;

use App\Entity\Listas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ListasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Listas::class,
        ]);
    }
}

src/Controller/ListasController.php
<?php

namespace App\Controller;

use App\Entity\Listas;
use App\Entity\Usuario;
use App\Form\ListasType;
use App\Repository\ListasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/listas")
 */
class ListasController extends AbstractController
{

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="listas_index", methods={"GET"})
     */
    public function index(ListasRepository $listasRepository): Response
    {
        return $this->render('listas/index.html.twig', [
            'listas' => $listasRepository->findBy(['usuario' => $this->session->get('idUser')]),
        ]);
    }

    /**
     * @Route("/new", name="listas_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lista = new Listas();
        $form = $this->createForm(ListasType::class, $lista);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $lista->setFechaCreacion(new \DateTime());

            $repository = $this->getDoctrine()->getRepository(Usuario::class);
            $usuario = $repository->find($this->session->get('idUser'));

            $lista->setUsuario($usuario);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lista);
            $entityManager->flush();

            return $this->redirectToRoute('tareas_index', ['id' => $lista->getId()]);
        }

        return $this->render('listas/new.html.twig', [
            'lista' => $lista,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="listas_show", methods={"GET"})
     */
    public function show(Listas $lista): Response
    {
        return $this->render('listas/show.html.twig', [
            'lista' => $lista,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="listas_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Listas $lista): Response
    {
        $form = $this->createForm(ListasType::class, $lista);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('listas_index');
        }

        return $this->render('listas/edit.html.twig', [
            'lista' => $lista,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="listas_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Listas $lista): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lista->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lista);
            $entityManager->flush();
        }

        return $this->redirectToRoute('listas_index');
    }
}

templates/listas/_delete_form.html.twig
<form method="post" action="{{ path('listas_delete', {'id': lista.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lista.id) }}">
    <button class="btn">Delete</button>
</form>

templates/listas/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/listas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Listas{% endblock %}

{% block body %}
    <h1>Edit Listas</h1>

    {{ include('listas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('listas_index') }}">back to list</a>

    {{ include('listas/_delete_form.html.twig') }}
{% endblock %}

templates/listas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listas
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/utilities.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
    <div class="top">
        <h3>Listas</h3>
        <a class="btn-large waves-effect waves-light red" href="{{ path('listas_new') }}">Nueva lista</a>
    </div>
	
    
	<div class="row">
		{% for lista in listas %}
			<div class="col s12 m4">
				<div class="card blue lighten-4">
					<div class="card-content">
						<span class="card-title">{{ lista.nombre }}</span>
					</div>
                    <div class="card-action">
                        <a href="{{ path('tareas_index') }}?id={{lista.id}}">Ver tareas</a>
                    </div>
				</div>
			</div>

		{% else %}
			<p>No hay listas disponibles</p>
		{% endfor %}
	</div>
{% endblock %}

templates/listas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nueva lista{% endblock %}

{% block body %}
    <div class="back-title">
        <a class="waves-effect blue lighten-4 btn-flat btn-back" href="{{ path('listas_index') }}"><i class="material-icons">keyboard_arrow_left</i></a>
        <h4>Crear lista</h4>
    </div>
    {{ include('listas/_form.html.twig') }}

    
{% endblock %}

templates/listas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listas{% endblock %}

{% block body %}
    <h1>Listas</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lista.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ lista.nombre }}</td>
            </tr>
            <tr>
                <th>Fecha_creacion</th>
                <td>{{ lista.fechaCreacion ? lista.fechaCreacion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('listas_index') }}">back to list</a>

    <a href="{{ path('listas_edit', {'id': lista.id}) }}">edit</a>

    {{ include('listas/_delete_form.html.twig') }}
{% endblock %}